### ISSUE TITLE
Test Compatibility with spigot 1.8+ and protocollib

### ISSUE THREAD

**Issue by drjawa** [Civcraft/AttrHider#5]
It might be possible that newer versions of protocollib work + need to see if the plugin itself needs any fixing beyond the usual for 1.8.

Putting it on my TODO list. Not high priority, but would be nice to nerf these features in hacked clients.

**Comment by Squeenix** [comment]
From Protocolllib 3.4 page (http://dev.bukkit.org/bukkit-plugins/protocollib/files/32-protocol-lib-3-4-0/):

THIS VERSION IS NOT COMPATIBLE WITH 1.8, DO NOT DOWNLOAD IT IF YOU ARE USING 1.8!  Apparently 1.710 broke some compatibilities?

I know it worked correctly on CivPVP for a long time after I wrote it, so that might be the issue.

**Comment by ProgrammerDan** [comment]
Soerxpso has been poking at this, feel free to grab him and involve him in this.

**Comment by suirad** [comment]
Good to close?
